stages:
  - build
  - deploy

build_docker:
  tags:
   - main
  retry: 2
  stage: build
  before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN
  script:
    - docker build --no-cache --compress --force-rm  -t $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
  after_script:
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker rmi  $CI_REGISTRY_IMAGE:latest
    - docker rmi $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    refs:
      - tags
  except:
    - branches

deploy_docker:
  image: gitlab.local.boshrapardaz.ir:4567/registry/alpine_ssh:latest
  when: on_success
  retry: 2
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p 22 -4 192.168.10.124 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIV_KEY" | tr -d '\r' | ssh-add -
  script:
    - ssh -T boshra@192.168.10.124 -p22 "cd /opt/reindex/ && docker-compose pull && docker-compose up -d "
  only:
    refs:
      - tags
  except:
    - branches
  tags:
    - ssh


